---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: root
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  tls:
  - hosts:
    - dev.6f.io
    secretName: root-tls
  rules:
  - host: dev.6f.io
    http:
      paths:
      - backend:
          serviceName: root
          servicePort: 80
