---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kipp
  namespace: production
spec:
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 1
  selector:
    matchLabels:
      app: kipp
  template:
    metadata:
      labels:
        app: kipp
    spec:
      containers:
      - name: kipp
        image: uhthomas/kipp:1590623331
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /aws-config
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: kipp
              key: database
        args: [
          "--database", "$(DATABASE)",
          "--filesystem", "s3://fr-par/kipp?endpoint=s3.fr-par.scw.cloud",
          "--lifetime", "0"
        ]
        resources:
          requests:
            memory: 16Mi
            cpu: 50m
          limits:
            memory: 64Mi
            cpu: 100m
        volumeMounts:
        - name: kipp
          mountPath: /aws-config
          readOnly: true
          subPath: aws-config
      volumes:
      - name: kipp
        secret:
          secretName: kipp
