---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kipp
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
spec:
  tls:
  - hosts:
    - kipp.6f.io
    secretName: kipp-tls
  rules:
  - host: kipp.6f.io
    http:
      paths:
      - backend:
          serviceName: kipp
          servicePort: 80
