---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  releaseName: grafana
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: grafana
    version: 5.0.26
  values:
    image:
      tag: 7.0.1
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Admin
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
          grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
        nginx.ingress.kubernetes.io/auth-url: https://sso.6f.io/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://sso.6f.io/oauth2/start?rd=https://$host$request_uri
      tls:
      - hosts:
        - grafana.6f.io
        secretName: grafana-tls
      hosts:
      - grafana.6f.io
      podAnnotations:
        linkerd.io/inject: enabled
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki:3100
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus
    persistence:
      enabled: true
    deploymentStrategy:
      type: Recreate
    plugins:
    - grafana-kubernetes-app