---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: root
  namespace: root-dev
spec:
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 1
  selector:
    matchLabels:
      app: root
  template:
    metadata:
      labels:
        app: root
    spec:
      containers:
      - name: root
        image: ghcr.io/uhthomas/6f.io@sha256:sha256:d5ce4021a051559bb7826401678642e982d42ee61c8b068ca2d17f95345652a0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 2Mi
            cpu: 2m
          limits:
            memory: 8Mi
            cpu: 5m
