---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: root
  namespace: root-dev
spec:
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 1
  selector:
    matchLabels:
      app: root
  template:
    metadata:
      labels:
        app: root
    spec:
      containers:
      - name: root
        image: ghcr.io/uhthomas/6f.io@sha256:5c7b60348e60995d8d238d80ad8edcc490589ac63fe7ea18140e42d1a78e84c1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 2Mi
            cpu: 2m
          limits:
            memory: 8Mi
            cpu: 5m
