---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  releaseName: elasticsearch
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: elasticsearch
    version: 1.39.0
  values:
    controller:
      autoscaling:
        enabled: true
      publishService:
        enabled: true