---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adya
  namespace: production
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.sfc: semver:*
spec:
  replicas: 1
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120
  strategy:
    type: Recreate
  minReadySeconds: 1
  selector:
    matchLabels:
      app: adya
  template:
    metadata:
      labels:
        app: adya
    spec:
      containers:
      - name: adya
        image: docker.pkg.github.com/uhthomas/adya/adya:v1.0.2
        imagePullPolicy: Always
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: adya
              key: token
        resources:
          requests:
            memory: 2Mi
            cpu: 2m
          limits:
            memory: 8Mi
            cpu: 5m
      imagePullSecrets:
      - name: regcred
