---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: root
  namespace: root
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - 6f.io
    secretName: root-tls
  rules:
  - host: 6f.io
    http:
      paths:
      - backend:
          service:
            name: root
            port:
              name: http
