---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kipp
  namespace: kipp
spec:
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 1
  selector:
    matchLabels:
      app: kipp
  template:
    metadata:
      labels:
        app: kipp
    spec:
      containers:
      - name: kipp
        # v0.1.2
        image: uhthomas/kipp@sha256:1da81b664eb09b327d3fee3e7eec28f8dd1c385d9e23cb57c5d236c38c209e1e
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /aws-config
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: kipp
              key: database
        args:
        - --database=$(DATABASE)
        - --filesystem=s3://fr-par/kipp?endpoint=s3.fr-par.scw.cloud
        - --lifetime=0
        resources:
          requests:
            memory: 16Mi
            cpu: 150m
          limits:
            memory: 64Mi
            cpu: 400m
        volumeMounts:
        - name: kipp
          mountPath: /aws-config
          readOnly: true
          subPath: aws-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: kipp
        secret:
          secretName: kipp
