---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kipp
  namespace: dev
spec:
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 1
  selector:
    matchLabels:
      app: kipp
  template:
    metadata:
      labels:
        app: kipp
    spec:
      containers:
      - name: kipp
        image: uhthomas/kipp@sha256:d73c739a05ee2b7da0bf0204ed7d0cfdfff5b4283f4e0cccbbdbd5ff18860243
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /aws-config
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: kipp
              key: database
        args: ["--database", "$(DATABASE)", "--filesystem", "s3://fr-par/kipp-dev?endpoint=s3.fr-par.scw.cloud"]
        resources:
          requests:
            memory: 24Mi
            cpu: 5m
          limits:
            memory: 32Mi
            cpu: 10m
        volumeMounts:
        - name: kipp
          mountPath: /aws-config
          readOnly: true
          subPath: aws-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: kipp
        secret:
          secretName: kipp
