---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kipp-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  tls:
  - hosts:
    - kipp.dev.6f.io
    secretName: kipp-tls
  rules:
  - host: kipp.dev.6f.io
    http:
      paths:
      - backend:
          serviceName: kipp
          servicePort: 80