---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: query-frontend
  namespace: thanos
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/auth-url: https://sso.6f.io/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://sso.6f.io/oauth2/start?rd=https://$host$request_uri
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - thanos.6f.io
    secretName: query-frontend-tls
  rules:
  - host: thanos.6f.io
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: query-frontend
            port:
              name: http
