---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kipp
  namespace: kipp-dev
spec:
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 1
  selector:
    matchLabels:
      app: kipp
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: kipp
    spec:
      containers:
      - name: kipp
        # v0.2.0
        image: uhthomas/kipp@sha256:584de5f2501506d18d1db84aeb503e73fffea57e374dd5f7863d019f65eca2c8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /aws-config
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: kipp
              key: database
        args:
        - --database=$(DATABASE)
        - --filesystem=s3://fr-par/kipp-dev?endpoint=s3.fr-par.scw.cloud
        resources:
          requests:
            memory: 16Mi
            cpu: 150m
          limits:
            memory: 64Mi
            cpu: 400m
        volumeMounts:
        - name: kipp
          mountPath: /aws-config
          readOnly: true
          subPath: aws-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: kipp
        secret:
          secretName: kipp
