---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: grafana
spec:
  releaseName: loki
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki
    version: 0.29.0
  values:
    podAnnotations:
      linkerd.io/inject: enabled
    persistence:
      enabled: true